spring:
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**,.h2.server.properties
    livereload:
      enabled: false # we use Webpack dev server + BrowserSync for livereload
  jackson:
    serialization:
      indent-output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:zyglWeb
    username: yu
    password:
      schema: classpath:/db/schema.sql
      data: classpath:/db/data.sql
    hikari:
      poolName: Hikari
      auto-commit: false
#      jdbc-url: jdbc:h2:file:c:/temp/zyglDB;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1
    #        datasource 使用HikariDataSource 时，一定是 jdbc-url不能是url
    #        加入AUTO_SERVER=TRUE 可以在web控制台中同时打开zygl,前题是当使用自动混合模式，所有客户端都需要使用同样的URL进行连接（不管它是一个本地还是一个远程连接。
    #        jdbc-url: jdbc:h2:file:c:/temp/zyglWeb;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1

  h2:
    console:
      enabled: true      # 开启 h2 web consloe，默认为 false
      path: /h2-console   # h2 web consloe 路径
      settings:
        web-allow-others: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    # Remove 'faker' if you do not want the sample data to be loaded automatically
    contexts: dev, faker
  mail:
    host: localhost
    port: 25
    username:
    password:
  messages:
    cache-duration: PT1S # 1 second, see the ISO 8601 standard
  thymeleaf:
    cache: false

server:
  port: 8082


