spring:
    #  profiles:
    #    active: dev
    devtools:
        restart:
            enabled: true
            additional-exclude: static/**,.h2.server.properties
        livereload:
            enabled: false # we use Webpack dev server + BrowserSync for livereload
    jackson:
        serialization:
            indent-output: true
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:h2:mem:zyglDB
        username: yu
        password: yu
        schema: classpath:/db/schema.sql
        data: classpath:/db/data.sql
        sql-script-encoding: utf-8
        platform: h2
        driverClassName: org.h2.Driver
        hikari:
            poolName: Hikari
            auto-commit: true
        #      jdbc-url: jdbc:h2:file:c:/temp/zyglDB;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1
        #      jdbc-url: jdbc:h2:file:c:/temp/zyglDB;DB_CLOSE_ON_EXIT=TRUE;FILE_LOCK=NO
        #        datasource 使用HikariDataSource 时，一定是 jdbc-url不能是url
        #        加入AUTO_SERVER=TRUE 可以在web控制台中同时打开zygl,前题是当使用自动混合模式，所有客户端都需要使用同样的URL进行连接（不管它是一个本地还是一个远程连接。
        #        jdbc-url: jdbc:h2:file:c:/temp/zyglWeb;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1

    h2:
        console:
            enabled: true      # 开启 h2 web consloe，默认为 false
            path: /h2   # #进行该配置，你就可以通过YOUR_URL/h2访问h2 web consloe。YOUR_URL是你程序的访问URl。
            settings:
                web-allow-others: true # 进行该配置后，h2 web consloe就可以在远程访问了。否则只能在本机访问。
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        show-sql: true
        hibernate:
            ddl-auto: update
        #liquibase:
        # Remove 'faker' if you do not want the sample data to be loaded automatically
        #contexts: dev, faker
    messages:
        cache-duration: PT1S # 1 second, see the ISO 8601 standard
server:
    port: 9088
    address: 11.11.126.69