-- delete from vehicle_state;
-- insert into vehicle_state values('1','1','在用', '车辆正常运行');
-- insert into vehicle_state values('2','2','停用', '车辆停止运行');
-- insert into vehicle_state values('3','3','待修', '车辆维修');
